# Generated by Django 4.1.3 on 2022-11-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='name', max_length=20)),
                ('apellido', models.CharField(default='apellido', max_length=20)),
                ('edad', models.IntegerField(default=0)),
                ('fec_nac', models.DateTimeField(default='2022-00-00 00:00:00.00000')),
            ],
        ),
    ]
