# Generated by Django 4.1.3 on 2022-12-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntregable1', '0002_alter_grupofamiliar_fec_nac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='name', max_length=20)),
                ('pais', models.CharField(default='pais', max_length=20)),
                ('fec_fundacion', models.DateField(default='2022-00-00')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='name', max_length=20)),
                ('apellido', models.CharField(default='apellido', max_length=20)),
                ('edad', models.IntegerField(default=0, max_length=2)),
                ('pais', models.CharField(default='pais', max_length=20)),
                ('equipo', models.CharField(default='libre', max_length=20)),
                ('posicion', models.CharField(default='libre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='name', max_length=20)),
                ('apellido', models.CharField(default='apellido', max_length=20)),
                ('edad', models.IntegerField(default=0, max_length=2)),
                ('pais', models.CharField(default='pais', max_length=20)),
                ('equipo', models.CharField(default='libre', max_length=20)),
            ],
        ),
    ]
